import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar/Navbar";
import { ToastProvider } from "@/components/AppToast/ToastNotification";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body suppressHydrationWarning className="flex h-full flex-col overflow-hidden">
                <AuthProvider>
                    <ToastProvider>
                        <Navbar />
                        <main className="flex min-h-0 flex-1 flex-col pt-18">
                            {children}
                        </main>
                    </ToastProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
